### ISSUE TITLE
Connection refused - connect(2) for "api-content.dropbox.com" port 443 (Errno::ECONNREFUSED)

### ISSUE THREAD

**Issue by floehopper** [freerange/trello_backup#1]
```
# trello_backup.log
I, [2015-02-11T02:00:01.354858 #17647]  INFO -- : Loading environment...
I, [2015-02-11T02:00:02.551011 #17647]  INFO -- : OK
I, [2015-02-11T02:00:03.151022 #17647]  INFO -- : 53c696d4571f05f4aba78a17 - Fetching Trello data for board...
I, [2015-02-11T02:00:03.831347 #17647]  INFO -- : 53c696d4571f05f4aba78a17 - OK
I, [2015-02-11T02:00:03.831472 #17647]  INFO -- : 53c696d4571f05f4aba78a17 - Writing data to Dropbox...
I, [2015-02-11T02:00:05.172126 #17647]  INFO -- : 53c696d4571f05f4aba78a17 - OK
I, [2015-02-11T02:00:05.172685 #17647]  INFO -- : 53b2c4cd6c86e16958978b33 - Fetching Trello data for board...
I, [2015-02-11T02:00:08.657948 #17647]  INFO -- : 53b2c4cd6c86e16958978b33 - OK
I, [2015-02-11T02:00:08.658088 #17647]  INFO -- : 53b2c4cd6c86e16958978b33 - Writing data to Dropbox...
I, [2015-02-11T02:00:10.198237 #17647]  INFO -- : 53b2c4cd6c86e16958978b33 - OK
I, [2015-02-11T02:00:10.198746 #17647]  INFO -- : 5092651ba6d669c174005fc0 - Fetching Trello data for board...
I, [2015-02-11T02:00:17.538996 #17647]  INFO -- : 5092651ba6d669c174005fc0 - OK
I, [2015-02-11T02:00:17.539131 #17647]  INFO -- : 5092651ba6d669c174005fc0 - Writing data to Dropbox...
/usr/lib/ruby/2.1.0/net/http.rb:879:in `initialize': Connection refused - connect(2) for "api-content.dropbox.com" port 443 (Errno::ECONNREFUSED)
        from /usr/lib/ruby/2.1.0/net/http.rb:879:in `open'
        from /usr/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
        from /usr/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
        from /usr/lib/ruby/2.1.0/net/http.rb:878:in `connect'
        from /usr/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
        from /usr/lib/ruby/2.1.0/net/http.rb:852:in `start'
        from /usr/lib/ruby/2.1.0/net/http.rb:1369:in `request'
        from /home/trello_backup/app/vendor/gems/ruby/2.1.0/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
        from /home/trello_backup/app/vendor/gems/ruby/2.1.0/gems/dropbox-sdk-1.6.4/lib/dropbox_sdk.rb:87:in `do_http'
        from /home/trello_backup/app/vendor/gems/ruby/2.1.0/gems/dropbox-sdk-1.6.4/lib/dropbox_sdk.rb:165:in `do_http'
        from /home/trello_backup/app/vendor/gems/ruby/2.1.0/gems/dropbox-sdk-1.6.4/lib/dropbox_sdk.rb:196:in `do_http_with_body'
        from /home/trello_backup/app/vendor/gems/ruby/2.1.0/gems/dropbox-sdk-1.6.4/lib/dropbox_sdk.rb:211:in `do_put'
        from /home/trello_backup/app/vendor/gems/ruby/2.1.0/gems/dropbox-sdk-1.6.4/lib/dropbox_sdk.rb:818:in `put_file'
        from backup.rb:54:in `block in <main>'
        from backup.rb:29:in `each'
        from backup.rb:29:in `<main>'
```

**Comment by floehopper** [comment]
I've just run this script successfully from my local machine using Ruby 2.1.0 and it worked fine, although I ended up generating a new Dropbox app OAuth token, because I was following along with the instructions in the README. I've updated the token on the production machine to match, because I think there is only ever a single valid token and I didn't want the cron job to start failing because it had the wrong token.

I can only assume this was a temporary connectivity problem, particularly since the cron job had successfully backed up two of the boards before it failed.

Closing.
